# Generated by Django 4.1.1 on 2022-09-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbase',
            options={'verbose_name': 'Accounts', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AddField(
            model_name='userbase',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
