# Generated by Django 4.1.1 on 2022-09-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userbase_options_userbase_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='phone',
            field=models.CharField(default='125469032', max_length=150),
        ),
    ]
