# Generated by Django 4.1.1 on 2022-09-21 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userbase_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='inveate',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('create', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='invite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitation',
            },
        ),
    ]
