# Generated by Django 4.1.1 on 2022-09-22 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userbase_inveate_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='create',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='phone',
            field=models.FloatField(),
        ),
    ]
