# Generated by Django 4.1.1 on 2022-09-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_invitation_create_alter_invitation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='phone',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
